config/routes.rb
AuthDemo::Application.routes.draw do
  resource :session, only: [:create, :destroy, :new]
  resource :user, only: [:create, :new, :show] do
    resource :counter, only: [:update]
  end
  resources :pages, only: :show
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    # no user with given username
    return nil if user.nil?

    # check user's password
    user.password_digest.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    # fetches the user we've logged in as
    return nil if self.session[:session_token].nil?
    @user ||= User.find_by(session_token: self.session[:session_token])
  end

  def log_in!(user)
    # force other clients to log out by regenerating token
    user.reset_session_token!
    # log this client in
    self.session[:session_token] = user.session_token
  end

  def log_out!
    self.session[:session_token] = nil
  end
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  def update
    current_user.counter = params[:user][:counter]
    current_user.save!
    redirect_to user_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    render template: "pages/#{params[:id]}"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # signs a user in
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      # no user with the given name!
      render :new
    else
      # sign the user in
      log_in!(@user)
      redirect_to user_url
    end
  end

  def destroy
    # sign a user out
    log_out!
    redirect_to new_session_url
  end

  def new
    # presents a login form
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    # sign up the user
    @user = User.new(user_params)
    if @user.save
      # redirect them to the new user's show page
      log_in!(@user)
      redirect_to user_url
    else
      # input didn't pass validation; re-render sign up form.
      render :new
    end
  end

  def new
    # present form for signup
    @user = User.new # dummy user object
    render :new
  end

  def show
    # show the user's details (just their username)
    if current_user.nil?
      # let them log in
      redirect_to new_session_url
      return
    end

    @user = current_user
    render :show
  end

  protected
  def user_params
    self.params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<nav class="navbar navbar-default">
<div class="container_fliud">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#collapse-menu"
            aria-expanded="false">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <div class="collapse navbar-collapse" id="collapse-menu">
    <ul class="nav navbar-nav pull-left">
      <li><a href="<%= page_url("home") %>">Home</a></li>
      <li><a href="<%= page_url("contact") %>">Contact</a></li>
      <li><a href="<%= page_url("about") %>">About</a></li>
    </ul>
    <ul class="nav navbar-nav pull-right">


    <% if current_user %>
      <li><a href="/user">Account</a></li>
      <li><a data-method='delete' href="<%= session_url %>">Logout</a></li>
    <% else %>
      <li><a href="<%= new_user_url %>">Sign Up</a></li>
      <li><a href="<%= new_session_url %>">Login</a></li>
    <% end %>
    </ul>
  </div>
</div>
</nav>
<body>
<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Project Bootstrap <small>Weekend 4</small></h1>
    <div class="col-xs-6">

      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
    </div>

  </div>
</div>
<div class="row">
  <h1>meet the team</h1>
  <div class="col-xs-3">
    <h1>Pudge</h1>
    <h2>
      <img src="http://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9f/Pudge.png?version=5b76eeddc9ff60a553d8ecdebbd45d82"
            alt="..."
            WIDTH="180"
            class="img-responsive img-circle">
    </h2>
  </div>
  <div class="col-xs-3">
    <h1>Invoker</h1>
    <h2>
      <img src="http://hydra-media.cursecdn.com/dota2.gamepedia.com/3/39/Invoker.png?version=cc2a440da5178b1ebbf2778cba02b9b2"
            alt="..."
            WIDTH="180"
            class="img-responsive img-circle">
    </h2>
  </div>
  <div class="col-xs-3">
    <h1>Necrophos</h1>
    <h2>
      <img src="http://hydra-media.cursecdn.com/dota2.gamepedia.com/1/13/Necrophos.png?version=6a7322564b0be5880c98d3ba32ecae1c"
            alt="..."
            WIDTH="180"
            class="img-responsive img-circle">
    </h2>
  </div>
  <div class="col-xs-3">
    <h1>Furion</h1>
    <h2>

      <img src="http://hydra-media.cursecdn.com/dota2.gamepedia.com/a/aa/Nature's_Prophet.png?version=53aea750ccdf3b838f9b1a15f7a2c043"

            WIDTH="180"
            class="img-responsive img-circle">


    </h2>
  </div>
</div>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<div class="row">
  <div class="col-xs-6">
    <form>
      <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" name="name" value="">
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" name="email" value="">
      </div>
      <div class="form-group">
        <label for="message">Message</label>
        <textarea class="form-control" name="message" rows="6">This is a dummy contact form.</textarea>
      </div>
      <button type="button" class="btn btn-primary">Submit</button>
    </form>
  </div>
  <div class="col-xs-6">
    <address>
      <strong>Colinology, Inc.</strong><br>
      1 Polk St<br>
      San Francisco, CA 94102<br>
      <abbr title="Phone">P:</abbr> (123) 456-7890
    </address>

    <address>
      <strong>Colin Chen</strong><br>
      <a href="mailto:#">colin.chen@colinology.com</a>
    </address>

    <address>
      <strong>Paulie Izzi</strong><br>
      <a href="mailto:#">paulie.izzi@colinology.com</a>
    </address>

  </div>
</div>

app/views/pages/home.html.erb
<h1>Home</h1>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-1">
  <h1>Sign up!</h1>

  <ul>
    <% @user.errors.full_messages.each do |err_msg| %>
      <li><%= err_msg %></li>
    <% end %>
  </ul>

  <form action="/user" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <div class="form-group">
      <label for="user_username">Username</label>
      <input
        type="text"
        name="user[username]"
        class="form-control"
        id="user_username"
        value="<%= @user.username %>">
    </div>
    <br>
    <div class="form-group">
      <label for="user_password">Password</label>
      <input
        type="password"
        name="user[password]"
        class="form-control"
        id="user_password">
    </div>
    <br>


    <button type="submit" class="btn btn-primary">Create User!</button>
  </form>
</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, <%= @user.username %></p>

<p>Current Counter Value: <%= @user.counter %></p>

<form action="/user/counter" method="POST">
  <input type="hidden" name="_method" value="PUT">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="user_counter">New Counter Value</label>
  <input type="number" name="user[counter]" id="user_counter">

  <input type="submit" value="Update Counter!">
</form>

<form action="/session" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="submit" value="Logout!">
</form>